### ISSUE TITLE
비디오 업로드시 파일을 드로그하면 파일이 실행되는 현상

### ISSUE THREAD

**Issue by KimJye** [connect-foundation/2019-10#208]

**Comment by hyokualexkwon** [comment]
파일 자체를 브라우저에 드래그하게 되면, 브라우저가 현재 탭 url이 파일 경로를 바라보기 때문에 발생하는 현상입니다. 현재 업로드 ui는 드래그 이벤트 핸들링이 되지 않기 때문에 당연히 드래그를 통한 파일 선택이 되지 않습니다.
